/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef light_CONSTANTS_H
#define light_CONSTANTS_H

#include "light_types.h"



class lightConstants {
 public:
  lightConstants();

};

extern const lightConstants g_light_constants;



#endif
